package org.rampart

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonPrimitive
import java.util.UUID

/**
 * A filter described in a sentence, turned into a real rule.
 *
 * "If I get a DMARC notification, mark it read and delete it" is a thing anybody can say
 * and almost nobody wants to build out of a field, a comparator and a folder picker. This
 * is the one place a model earns its keep in a mail client: the person knows exactly what
 * they want and the tedious part is expressing it.
 *
 * **The model does not write Sieve.** It fills in the same JSON shape Bulwark's metadata
 * already uses, and [ruleOf] parses it exactly as it parses a rule read off the server.
 * The script is then generated by the same compiler every other rule goes through. Three
 * things follow from that, and they are the reason it is built this way:
 *
 * - Whatever the model returns either becomes a rule this build fully understands, or is
 *   refused. There is no path where a hallucinated line reaches the server.
 * - The output matches the server's own syntax by construction, rather than by the model
 *   having been told about it and hopefully complying.
 * - Turning the assistant off changes nothing about the rules already made. They are
 *   ordinary Sieve on the server, editable in the builder and in Bulwark, and they keep
 *   running with the model gone forever.
 *
 * Nothing is saved without being shown first. A generated rule is a suggestion, in a
 * sentence, with a button: a filter that deletes mail is not something to find out about
 * afterwards.
 */

/** What the model is allowed to produce, which is exactly what this build can execute. */
internal fun ruleSystem(folders: List<String>): String = buildString {
    appendLine("You turn one sentence into one mail filter rule, as JSON and nothing else.")
    appendLine()
    appendLine("Answer in this shape:")
    appendLine(
        """{"name":"short name","matchType":"all","stopProcessing":false,""" +
            """"conditions":[{"field":"from","comparator":"contains","value":"text"}],""" +
            """"actions":[{"type":"move","value":"Folder"}]}""",
    )
    appendLine()
    appendLine("field: from, to, cc, subject, body. Nothing else exists.")
    appendLine("comparator: contains, is, starts_with, ends_with. Nothing else exists.")
    appendLine("matchType: all when every condition must match, any when one is enough.")
    appendLine(
        "actions, one or more: {\"type\":\"move\",\"value\":\"Folder\"}, " +
            "{\"type\":\"tag\",\"value\":\"word\"}, {\"type\":\"mark_read\"}, " +
            "{\"type\":\"mark_flagged\"}, {\"type\":\"delete\"}.",
    )
    appendLine()
    if (folders.isEmpty()) {
        appendLine("There are no folders to file into, so do not use move.")
    } else {
        appendLine("Folders that exist, spelled exactly: " + folders.joinToString(", ") + ".")
        appendLine("Never invent a folder.")
    }
    appendLine()
    appendLine(
        """If the sentence cannot be said with those fields, comparators and actions, """ +
            """answer {"error":"one sentence saying what is missing"} instead. Do not """ +
            """approximate it.""",
    )
    append("Answer with the JSON on its own. No explanation and no code fence.")
}

/** The exact bytes that would be sent, which is what the viewer shows before anything is. */
internal fun rulePacket(config: AssistantConfig, words: String, folders: List<String>): String =
    Llm.packet(config.model, ruleSystem(folders), words.trim(), maxTokens = 400)

/**
 * The answer, as a rule this build can run, or a sentence saying why not.
 *
 * Every refusal here is a sentence somebody can act on, because the alternative is a rule
 * that looks right and quietly does something else. The checks, in order: it has to be
 * JSON, it has to be a rule rather than a refusal, every part of it has to be one this
 * build understands, and a folder it files into has to exist.
 */
internal fun ruleOfAnswer(answer: String, folders: List<String>): Result<Rule> {
    // Models wrap JSON in a code fence however firmly they are asked not to. Taking what is
    // between the braces is cheaper than arguing with them about it.
    val body = answer.substringAfter('{', "").substringBeforeLast('}', "")
    if (body.isBlank()) return Result.failure(LlmError("The answer was not a rule."))
    val json = runCatching { lenient.parseToJsonElement("{$body}") as? JsonObject }.getOrNull()
        ?: return Result.failure(LlmError("The answer was not a rule."))

    json["error"]?.jsonPrimitive?.contentOrNull?.takeIf { it.isNotBlank() }?.let {
        return Result.failure(LlmError(it))
    }

    val rule = ruleOf(json) ?: return Result.failure(LlmError("The answer was not a rule."))
    if (rule.tests.isEmpty()) return Result.failure(LlmError("That rule had nothing to match on."))
    if (rule.acts.isEmpty()) return Result.failure(LlmError("That rule had nothing to do."))
    if (!rule.understood) {
        return Result.failure(LlmError("That used something Rampart cannot put in a rule yet."))
    }

    /*
     * A folder is corrected for case and otherwise refused.
     *
     * Sieve files into a name, and a name that is not quite a folder is a rule that either
     * fails at delivery or makes a folder nobody asked for, depending on the server. Case
     * is the one difference worth fixing silently: every other mismatch is the model having
     * invented somewhere to put the mail.
     */
    val acts = rule.acts.map { act ->
        if (act !is Act.FileInto) return@map act
        val real = folders.firstOrNull { it.equals(act.folder, ignoreCase = true) }
            ?: return Result.failure(LlmError("There is no folder called ${act.folder}."))
        Act.FileInto(real)
    }

    // A fresh id, never the model's. An id that collided with a rule already on the server
    // would replace it on the next save.
    return Result.success(
        rule.copy(
            id = UUID.randomUUID().toString(),
            name = rule.name.ifBlank { "New rule" },
            acts = acts,
            raw = null,
        ),
    )
}

private val lenient = Json { ignoreUnknownKeys = true; isLenient = true }
